experiment_name: "jailbreak_PGJ_stable-diffusion-3-medium"
output_dir: "benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

model:
  name: "stable-diffusion-3-medium"
  params:
    model_name: "stable-diffusion-3-medium"
    device: "cuda"


attack_method: "PGJ"

datasets:
  - "data/jailbreak_diffusion_bench/jailbreak_diffusion_bench.json"