[build-system]
requires = ["setuptools>=61.0"]

[project]
name = "jailbreakbench"
version = "0.1"
requires-python = ">= 3.10"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Security",
    "License :: OSI Approved :: MIT License",
    "Environment :: GPU",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["jailbreak", "benchmark", "llms", "jailbreakbench", "machine learning", "security"]
dependencies = [
    "litellm~=1.20.0",
    "pandas>=2.2.0,<3.0.0",
    "pydantic>=2.6.1,<3.0.0",
    "requests>=2.31.0,<3.0.0",
    "transformers>=4.38.0,<5.0.0",
    "setuptools>=61.0"
]

[project.optional-dependencies]
vllm = [
    "accelerate>=0.27.2,<1.0.0",
    "vllm~=0.3.2",
]
dev = ["ruff>=0.2.1,<1.0.0"]

[project.urls]
Homepage = "https://jailbreakbench.github.io"
Repository = "https://github.com/JailbreakBench/jailbreakbench.git"
Issues = "https://github.com/JailbreakBench/jailbreakbench/issues"

[tool.setuptools]
include-package-data = true
py-modules = []

[tool.ruff]
target-version = "py310"
line-length = 120
exclude = ["./data/"]

[tool.ruff.lint]
ignore = [
    "E731",
    "E402",
    "N812", # Uppercase import (for nn.functional as F)
]
select = [
    "F",   # pyflakes
    "UP",  # pyupgrade
    "I",   # isort
    "ERA", # eradicate
    "NPY", # numpy
    "N",   # pep8-naming
    "UP",  # pyupgrade
]

[tool.ruff.format]
docstring-code-format = true

[tool.mypy]
ignore_missing_imports = true
exclude = ["./data/"]
