[build-system]
requires = ["setuptools >= 61.0"]

[project]
name = "jailbreakbench"
version = "0.1"
dynamic = ["dependencies"]
requires-python = ">= 3.10"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Security",
    "License :: OSI Approved :: MIT License",
    "Environment :: GPU",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = ["jailbreak", "benchmark", "llms", "jailbreakbench", "machine learning", "security"]

[project.urls]
Homepage = "https://jailbreakbench.github.io"
Repository = "https://github.com/JailbreakBench/jailbreakbench.git"
Issues = "https://github.com/JailbreakBench/jailbreakbench/issues"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.ruff]
target-version = "py30"
line-length = 120
ignore = [
    "E731",
    "E402",
    "N812", # Uppercase import (for nn.functional as F)
]
select = [
    "F",   # pyflakes
    "UP",  # pyupgrade
    "I",   # isort
    "ERA", # eradicate
    "NPY", # numpy
    "N",   # pep8-naming
    "UP",  # pyupgrade
]
exclude = ["./data/"]

[tool.mypy]
plugins = "pydantic.mypy"
ignore_missing_imports = true
exclude = ["./data/"]