from diffusers.pipelines.stable_diffusion import safety_checker

print(safety_checker.__file__)

from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker

print(StableDiffusionSafetyChecker)