experiment_name: "jailbreak_MMA_stable-diffusion-v1-5"
output_dir: "benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

model:
  name: "stable-diffusion-v1-5"
  params:
    model_name: "stable-diffusion-v1-5"
    device: "cuda"


attack_method: "MMA"

datasets:
  - "data/jailbreak_diffusion_bench/jailbreak_diffusion_bench.json"