# config_stable-diffusion-3.5-large-turbo_noattack.yaml
experiment_name: "jailbreak_stable-diffusion-3.5-large-turbo_noattack"
output_dir: "/data3/user/jin509/data_diffusion_benchmark/jailbreak_diffusion/benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

model:
  name: "stable-diffusion-3.5-large-turbo"
  params:
    model_name: "stable-diffusion-3.5-large-turbo"
    device: "cuda"  


attack_method: "no_attack"

datasets:
  - data/benign/diffusion_db/diffusion_db_benign_6000.json




# stable-diffusion-v1-5
# stable-diffusion-2
# stable-diffusion-3.5-large-turbo
# stable-diffusion-xl-base-0.9
# stable-diffusion-3.5-medium
# stable-diffusion-safe
# flux-1-dev
# cogview3
# stable-diffusion-3.5-large
# stable-diffusion-3.5-large-turbo
# hunyuan-dit-v1.2-distilled