experiment_name: "jailbreak_PGJ_hunyuan-dit-v1.2-distilled"
output_dir: jailbreak_attack_results/PGJ/{model_name}  # Will be formatted with model name
log_level: INFO

results_path: benchmark_results/PGJ/stable-diffusion-3-medium/jailbreak_diffusion_bench_filtered_400/enriched_dataset.json


model:
  name: "hunyuan-dit-v1.2-distilled"
  attack_method: "PGJ"

  params:
    model_name: "hunyuan-dit-v1.2-distilled"
    device: "cuda"
