experiment_name: "jailbreak_PGJ_stable-diffusion-3.5-medium"
output_dir: jailbreak_attack_results/PGJ/{model_name}  # Will be formatted with model name
log_level: INFO

results_path: benchmark_results/PGJ/stable-diffusion-3-medium/jailbreak_diffusion_bench_filtered_400/enriched_dataset.json


model:
  name: "stable-diffusion-3.5-medium"
  attack_method: "PGJ"

  params:
    model_name: "stable-diffusion-3.5-medium"
    device: "cuda"
