experiment_name: "jailbreak_MMA_cogview3"
output_dir: jailbreak_attack_results/MMA/{model_name}  # Will be formatted with model name
log_level: INFO

results_path: benchmark_results/MMA/stable-diffusion-3.5-medium/jailbreak_diffusion_bench_filtered_400/enriched_dataset.json


model:
  name: "cogview3"
  attack_method: "MMA"
  params:
    model_name: "cogview3"
    device: "cuda"  # Will be overridden by CUDA_VISIBLE_DEVICES
