experiment_name: "jailbreak_MMA_hunyuan-dit-v1.2-distilled"
output_dir: jailbreak_attack_results/MMA/{model_name}  # Will be formatted with model name
log_level: INFO

results_path: benchmark_results/MMA/stable-diffusion-3.5-medium/jailbreak_diffusion_bench_filtered_400/enriched_dataset.json


model:
  name: "hunyuan-dit-v1.2-distilled"
  attack_method: "MMA"

  params:
    model_name: "hunyuan-dit-v1.2-distilled"
    device: "cuda"
