# evaluation_text_detector/config/evaluation_configs.yaml
datasets:
  i2p_filtered:
    path: "evaluation_text_detector/data/harmful/I2P/I2P_filtered_test.json"
    weight: 1.0

output_dir: "results"
batch_size: 32
num_workers: 4

metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  - average_precision


detectors:
  openai:
    model: "omni-moderation-latest"
