# evaluation_text_detector/config/evaluation_configs.yaml
datasets:
  dataset1:
    path: "data/dataset1/dataset_info.json"
    weight: 1.0


output_dir: "results"
batch_size: 32
num_workers: 4

metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  - average_precision