# evaluation_text_detector/config/text_evaluation_configs.yaml

data_dir: "evaluation_text_detector/data"

datasets:
  harmful:
    i2p:
      path: "data/harmful/I2P/I2P_filtered_test.json"

  benign:
    diffusion_db:
      path: data/benign/diffusion_db/diffusion_db-back.json




output_dir: "evaluation_text_detector/results"

batch_size: 32
num_workers: 4

save_misclassified: true


metrics:
  - accuracy
  - precision
  - recall
  - f1
  - auc
  - average_precision

detectors:
  openai_text_moderation: {}