experiment_name: "jailbreak_DACA_flux-1-dev"
output_dir: jailbreak_attack_results/DACA/{model_name}  # Will be formatted with model name
log_level: INFO

results_path: benchmark_results/DACA/stable-diffusion-3-medium/jailbreak_diffusion_bench_filtered_400/enriched_dataset.json

model:
  name: "flux-1-dev"
  attack_method: "DACA"
  params:
    model_name: "flux-1-dev"
    device: "cuda"