# evaluation_image_detector/config/openai_model.yaml
# Configuration for OpenAI model evaluation

data_dir: "evaluation_image_detector/data"

datasets:
  datasets:
    path: benchmark_results/no_attack/stable-diffusion-3.5-large-turbo/harmful/I2P

  datasets:
    path: benchmark_results/no_attack/stable-diffusion-3-medium/harmful/I2P

batch_size: 512
num_workers: 4

save_misclassified: true

metrics:
  - accuracy
  - precision
  - recall

detectors:
  aws_image_checker: {}
  