# evaluation_image_detector/config/evaluation_configs.yaml
datasets:
  test_dataset:
    path: "evaluation_image_detector/data/test/dataset_info.json"

output_dir: "results"
batch_size: 16
num_workers: 4
save_misclassified: true

metrics:
  - accuracy
  - precision
  - recall

detectors:
  openai:
    model: "omni-moderation-latest"
