# evaluation_image_detector/config/detector_configs.yaml
detectors:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: "gpt-4-vision-preview"
    max_tokens: 1000
    
  azure:
    key: ${AZURE_KEY}
    endpoint: ${AZURE_ENDPOINT}
    severity_threshold: 2
    
  google:
    credentials_path: ${GOOGLE_CREDENTIALS_PATH}
    project_id: ${GOOGLE_PROJECT_ID}
    
  aws:
    access_key: ${AWS_ACCESS_KEY}
    secret_key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    confidence_threshold: 0.8
    
  safety_checker:
    model_path: "path/to/safety/model"
    device: "cuda"
    threshold: 0.5