experiment_name: "jailbreak_sneakprompt_cogview3"

output_dir: "benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

# Single model configuration

model:
  name: "cogview3"
  params:
    model_name: "cogview3"
    device: "cuda"  

attack_method: "sneakprompt"

datasets:
  - "data/jailbreak_diffusion_bench/jailbreak_diffusion_bench_filtered_200.json"