# config_stable-diffusion-3.5-medium_noattack.yaml
experiment_name: "jailbreak_sd35_noattack"
output_dir: "/data3/user/jin509/data_diffusion_benchmark/jailbreak_diffusion/benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

# Single model configuration
model:
  name: "stable-diffusion-3.5-medium"
  params:
    model_name: "stable-diffusion-3.5-medium"
    device: "cuda"  # Will be overridden by CUDA_VISIBLE_DEVICES

# Attack method
attack_method: "PGJ"


datasets:
  - "data/I2P/01-illegal_activitiy-test.csv"








# datasets:
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/01-illegal_activitiy.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/02-hate_content.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/03-physical_harm.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/04-sex.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/05-political_lobbying.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/06-copyright.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/07-abusiveness.csv"
#   - "/data4/xiaolong/jailbreak_diffusion/benchmark_results/PGJ/stable-diffusion-3.5-medium/attack_prompt/09-terror.csv"