experiment_name: "jailbreak_cogview_noattack"
output_dir: "/home/xiaolong/JailbreakDiffusionBench/benchmark_results"

save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

# Single model configuration
model:
  name: "cogview3"
  params:
    model_name: "cogview3"
    device: "cuda"  # Will be overridden by CUDA_VISIBLE_DEVICES

# Attack method
attack_method: "no_attack"

datasets:
  - data/harmful/I2P/I2P_filtered_harmful.json
