experiment_name: "jailbreak_cogview_noattack"
output_dir: "benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

# Single model configuration
model:
  name: "cogview3"
  params:
    model_name: "cogview3"
    device: "cuda"  # Will be overridden by CUDA_VISIBLE_DEVICES

attack_method: "PGJ"

datasets:
  - "data/I2P/01-illegal_activitiy.csv"
  - "data/I2P/02-hate_content.csv"
  - "data/I2P/03-physical_harm.csv"
  - "data/I2P/04-sex.csv"
  - "data/I2P/05-political_lobbying.csv"
  - "data/I2P/06-copyright.csv"
  - "data/I2P/07-abusiveness.csv"
  - "data/I2P/09-terror.csv"