experiment_name: "jailbreak_PGJ_hunyuan-dit-v1.2-distilled"
output_dir: "benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

model:
  name: "hunyuan-dit-v1.2-distilled"
  params:
    model_name: "hunyuan-dit-v1.2-distilled"
    device: "cuda"


attack_method: "PGJ"

datasets:
  - "data/jailbreak_diffusion_bench/jailbreak_diffusion_bench.json"