experiment_name: "jailbreak_flux_noattack"
output_dir: "/home/xiaolong/JailbreakDiffusionBench/benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

# Single model configuration
model:
  name: "flux-1-dev"
  params:
    model_name: "flux-1-dev"
    device: "cuda"  # Will be overridden by CUDA_VISIBLE_DEVICES

# Attack method
attack_method: "no_attack"

# List of dataset paths
datasets:
  - "data/harmful/civitai/civitai_nsfw_prompts_2000.json"

