# config_stable-diffusion-safe_noattack.yaml
experiment_name: "jailbreak_stable-diffusion-safe_noattack"
output_dir: "/home/xiaolong/JailbreakDiffusionBench/benchmark_results"
save_images: true
save_prompts: true
log_level: "INFO"
batch_size: 1
num_workers: 1

model:
  name: "stable-diffusion-safe"
  params:
    model_name: "stable-diffusion-safe"
    device: "cuda"  


attack_method: "no_attack"

datasets:
  - "data/harmful/civitai/civitai_nsfw_prompts_2000.json"




# stable-diffusion-v1-5
# stable-diffusion-2
# stable-diffusion-safe
# stable-diffusion-xl-base-0.9
# stable-diffusion-3.5-medium
# stable-diffusion-safe
# flux-1-dev
# cogview3
# stable-diffusion-3.5-large
# stable-diffusion-3.5-large-turbo
# hunyuan-dit-v1.2-distilled