name: Upload Python Package on PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  lint-fmt-typecheck-test:
    uses: ./.github/workflows/lint.yml
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jailbreakbench
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"
      - name: Get uv cache dir
        id: uv-cache
        run: |
          echo "dir=$(uv cache dir)" >> $GITHUB_OUTPUT
          - name: uv cache
            uses: actions/cache@v4
            with:
              path: ${{ steps.uv-cache.outputs.dir }}
              key: ${{ runner.os }}-uv-${{ matrix.python-version }}-${{ hashFiles('**/requirements-dev.lock') }}
              restore-keys: |
                ${{ runner.os }}-uv-
      - name: Install dependencies
        run: |
          uv pip install -r requirements-dev.lock
          uv pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
